
import React from 'react'
import { Button } from '@/components/ui/button'
import { Download, FileText } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'

interface RecoveryPhrasePDFProps {
  recoveryPhrase: string[]
}

export function RecoveryPhrasePDF({ recoveryPhrase }: RecoveryPhrasePDFProps) {
  const { toast } = useToast()

  const generatePDF = () => {
    // Create PDF content
    const pdfContent = `
HARMONY OF GAIA - ADMIN RECOVERY PHRASE
=======================================

ULTRA SECURE 12-WORD RECOVERY PHRASE
=====================================

Generated: ${new Date().toLocaleString()}
Admin Email: info@cultureofharmony.net

RECOVERY WORDS (Store Securely):
================================

${recoveryPhrase.map((word, index) => `${(index + 1).toString().padStart(2, '0')}. ${word}`).join('\n')}

CRITICAL SECURITY INSTRUCTIONS:
===============================

1. Store this document in a secure, offline location
2. Make multiple physical copies and store them separately
3. Never share these words with anyone
4. Use this phrase to recover admin access on new devices
5. Keep this document away from digital storage when possible

RECOVERY PROCESS:
=================

To recover admin access:
1. Go to the admin recovery section
2. Enter all 12 words in the exact order shown above
3. Verify the phrase matches exactly
4. Admin privileges will be restored

WARNING: Anyone with access to these 12 words has complete control over the Harmony of Gaia admin system.

Culture of Harmony - Synatic!oul1992
Website: https://cultureofharmony.net
Generated by: Gaia's Exchanges Admin System
    `

    // Create and download the PDF as a text file (simple implementation)
    const blob = new Blob([pdfContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `Harmony_of_Gaia_Admin_Recovery_Phrase_${new Date().toISOString().split('T')[0]}.txt`
    
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

    toast({
      title: "📄 Recovery Phrase Document Created",
      description: "Your secure recovery phrase document has been downloaded",
    })
  }

  return (
    <div className="space-y-4">
      <Button
        onClick={generatePDF}
        className="w-full bg-blue-600 hover:bg-blue-700"
        disabled={!recoveryPhrase || recoveryPhrase.length !== 12}
      >
        <Download className="h-4 w-4 mr-2" />
        Download Recovery Phrase Document
      </Button>
      
      <div className="text-xs text-blue-300 bg-blue-500/10 border border-blue-500/20 rounded p-3">
        <div className="flex items-center gap-2 mb-1">
          <FileText className="h-3 w-3" />
          <span className="font-semibold">Document Security</span>
        </div>
        <p>The recovery phrase will be saved as a secure text document with complete instructions for admin recovery.</p>
      </div>
    </div>
  )
}
